- src/Adapter/PhpAcl.php
- src/Adapter/Utility/PhpAco.php
- src/Adapter/Utility/PhpAro.php
- src/Auth/BaseAuthorize.php
- src/Auth/CrudAuthorize.php
- src/Model/Behavior/AclBehavior.php
- src/Model/Table/AclNodesTable.php
- src/Model/Table/PermissionsTable.php
- tests/Fixture/AcoActionsFixture.php
- tests/Fixture/AcoTwosFixture.php
- tests/Fixture/AcosFixture.php
- tests/Fixture/AroTwosFixture.php
- tests/Fixture/ArosAcoTwosFixture.php
- tests/Fixture/ArosAcosFixture.php
- tests/Fixture/ArosFixture.php
- tests/TestCase/Adapter/DbAclTest.php
- tests/TestCase/Adapter/IniAclTest.php
- tests/TestCase/Adapter/PhpAclTest.php
- tests/TestCase/Auth/ActionsAuthorizeTest.php
- tests/TestCase/Auth/CrudAuthorizeTest.php
- tests/TestCase/Controller/Component/AclComponentTest.php
- tests/TestCase/Model/Behavior/AclBehaviorTest.php
- tests/TestCase/Model/Table/AclNodesTest.php
- tests/test_app/TestApp/Config/acl.php
Use short array syntax in code and example.
> use short array syntax

- src/Adapter/IniAcl.php
- src/Adapter/PhpAcl.php
- tests/TestCase/Adapter/IniAclTest.php
- tests/TestCase/Adapter/PhpAclTest.php
linked to cakephp/cakephp#5564
> remove config file extension

- config/bootstrap.php
- src/Model/Table/AclNodesTable.php
- src/Shell/AclShell.php
- tests/TestCase/Model/Table/AclNodesTest.php
- tests/bootstrap.php
Ref #30 
And i wanted ask if i can make the doc in FR (only FR, because my english is too bad :smile: ) for this plugin ?
If yes, should i do it in the cakephp/docs repo ?
> Fix the method to get the Entity

- src/AclExtras.php
- src/Shell/AclExtrasShell.php
- tests/TestCase/AclExtrasTest.php
While this doesn't fix everything, it is incremental progress :smile:
Refs #44
> Fix up a bunch of the PHPCS errors.

- src/AclExtras.php
- src/Auth/BaseAuthorize.php
- tests/TestCase/AclExtrasTest.php
- tests/TestCase/test_controllers.php
- tests/bootstrap.php
- tests/test_app/Plugin/Nested/TestPluginTwo/src/Controller/PluginTwoController.php
- tests/test_app/Plugin/TestPlugin/src/Controller/PluginController.php
Updated the Acl extras test and then corrected a number of issues related to plugins (Especially vendor namespaced ones).
> Corrects issues with Plugins and the ACL Extras shell

- src/Adapter/PhpAcl.php
> Fix DS typo.

- src/Model/Table/AclNodesTable.php
> Search for modelname when node is a plugin entity

- src/Shell/AclShell.php
- tests/TestCase/AclShellTest.php
Add test and fix setParent() method
> AclShell setParent() fix

- src/Model/Table/PermissionsTable.php
Account for string action passed in already prefixed with an '_'
> Account for string action passed in already prefixed with an '_'

- composer.json
Refs https://github.com/cakephp/bake/issues/268
> Add missing direct dependency

- src/Model/Behavior/AclBehavior.php
> Use method instead of property

- composer.json
- src/AclExtras.php
- tests/TestCase/AclExtrasTest.php
- tests/TestCase/Adapter/CacheDbAclTest.php
- tests/bootstrap.php
- tests/test_app/src/Controller/Admin/V10/Authors/Editors/DummyController.php
I don't know why, but this seem to work. :)
Closes #120
> WIP: Try to handle nested prefixes

- README.md
Adding a most basic instruction to get the behavior up-and-running (as the docs seem to have disappeared)
> Kickstart instructions

- .travis.yml
- src/Model/Table/AclNodesTable.php
- tests/bootstrap.php
Authored by @progLamer
Closes #125
> Fix query generation for postgresql

- src/AclExtras.php
- src/Adapter/CachedDbAcl.php
- src/Adapter/DbAcl.php
- src/Auth/BaseAuthorize.php
- src/Auth/CrudAuthorize.php
- src/Model/Behavior/AclBehavior.php
- src/Model/Table/AclNodesTable.php
- src/Shell/AclExtrasShell.php
- src/Shell/AclShell.php
- tests/TestCase/AclShellTest.php
- tests/TestCase/Adapter/DbAclTest.php
- tests/TestCase/Adapter/PhpAclTest.php
- tests/TestCase/Auth/ActionsAuthorizeTest.php
- tests/TestCase/Auth/CrudAuthorizeTest.php
- tests/TestCase/Model/Behavior/AclBehaviorTest.php
- tests/TestCase/Model/Table/AclNodesTest.php
- tests/test_app/config/acl.php
Removes usage of deprecations to make it work with cake 3.6 without deprecation warnings
> Remove usage of deprecations

- src/Shell/AclShell.php
>  Drop DbConfig task

- src/Shell/AclShell.php
> Adjust usage of deprecated methods

- src/Shell/AclShell.php
> Remove deprecated methods

- src/Shell/AclExtrasShell.php
I missed this in the previous pull request, my apologies.
> Assign shell via new setter instead of directly

- src/AclExtras.php
- src/Adapter/IniAcl.php
- src/Model/Table/PermissionsTable.php
We have missed a few declarations which will throw deprecation messages when using php 8.2
> Declare class properties for php 8.2
