cakephp/acl

README.md
src/Shell/AclExtrasShell.php
src/Shell/AclShell.php

- Remove initdb
- Add small note on running migrations to create tables
- Catch missing table errors and display above note

Remove initdb

---

.travis.yml
composer.json
src/AclExtras.php
src/Model/Table/AclNodesTable.php
src/Shell/AclExtrasShell.php
src/Shell/AclShell.php
tests/TestCase/AclExtrasTest.php
tests/TestCase/test_controllers.php

use short array syntax and remove plugin-installer dependency.
The travis phpcs change is to avoid the migrations files to be checked and also this rules is pretty much in every other repos.

fixes an other bunch of cs errors

---

src/Model/Table/AclNodesTable.php

Without a connection, when trying to get the Table, this would throw an exception if the users weren't in the default connection. This ensures that the connection set in the app config is respected when dealing with nodes.

Setting the connection when using nodes

---

src/AclExtras.php

It is possible to customize the app namespace, the aco_sync command should use the configured namespace rather than assuming it is 'App'

ACO Sync should take into account custom app namespace

---

src/AclExtras.php

$controllerName was wrong on windows environement it returns : 
\plugins\Acl\src\AclExtras.php (line 166)
########## DEBUG ##########
'C:\xampp\htdocs\Labs\acl\src\Controller\Pages'
###########################
Then I change explod char to DIRECTORY_SEPARATOR
Results : 
\plugins\Acl\src\AclExtras.php (line 166)
########## DEBUG ##########
'Pages'
###########################

Bug aco_sync, controllers not found

---

src/Shell/AclShell.php

fixing issue #47 - cake acl grant throws Unknown method "node" in ORM/Table; AclShell was forcing the TableRegistry to register a generic instance of Aros table

fixing issue #47 - cake acl grant throws Unknown method "node"

---

src/AclExtras.php
src/Shell/AclExtrasShell.php
tests/TestCase/AclExtrasTest.php

This method is no longer offered by the core TreeBehavior, Acl plugin also does not implement these features.
Refs #52

Remove verify()

---

src/Model/Table/AclNodesTable.php

The connection option takes an instance, not a string name.
Refs cakephp/cakephp#6199

Fix incorrect connection option usage.

---

src/Model/Table/AclNodesTable.php
tests/TestCase/Model/Table/AclNodesTest.php

This will add the ability to pass an int to the `node` method, which will be used to search the corresponding ACO/ARO. This is for example useful for when you're creating permissions through the console, and you only want to define the ID of the ACO/ARO (when you got it from `aco view` or your database).

Add ability to pass ID to node method

---

.travis.yml
README.md
composer.json
phpunit.xml.dist
tests/TestCase/AclExtrasTest.php

Bumps min cakephp version to 3.0.1 (first version with PHP7 support), and adds tests for PHP7, Codecov support and a minimum version test.

Update travis and composer

---

phpcs.xml.dist
src/AclExtras.php
src/Adapter/IniAcl.php
src/Adapter/Utility/PhpAco.php
src/Adapter/Utility/PhpAro.php
src/Auth/ActionsAuthorize.php
src/Auth/CrudAuthorize.php
src/Controller/Component/AclComponent.php
src/Model/Behavior/AclBehavior.php
src/Model/Table/AclNodesTable.php
src/Model/Table/ArosTable.php
src/Model/Table/PermissionsTable.php
src/Shell/AclExtrasShell.php
src/Shell/AclShell.php
tests/TestCase/AclExtrasTest.php
tests/TestCase/AclShellTest.php
tests/TestCase/Adapter/CacheDbAclTest.php
tests/TestCase/Auth/ActionsAuthorizeTest.php
tests/TestCase/Auth/CrudAuthorizeTest.php
tests/TestCase/Controller/Component/AclComponentTest.php
tests/TestCase/Model/Behavior/AclBehaviorTest.php

Modification based on deprecated message of PHPUnit (Fixed App::className: b90e7ab)
Modification based on the cakephp coding standerd 	(Fixed for phpcs: 74436f0)
Fixed $this->entityClass()  argument mistake.

Modification based on deprecated message of PHPUnit and modification based on the cakephp coding standerd

---

src/AclExtras.php
tests/TestCase/AclExtrasTest.php
tests/TestCase/test_controllers.php

This is a simple fix, using reflection in `AclExtras->_updateControllers` to confirm that a controller is instantiable before it is added to the list of ones that will be instantiated in `_checkMethods`.
Travis-CI shows failures, because every job that involves MySQL [fails to install it 5.5](https://travis-ci.org/mikeu/acl/jobs/181145416#L278-L280). The last successful push to the Acl repo (e5010b4) was on 25 November. Two days ago on 2 December, the OS details for the build image were changed from Ubuntu 14.04.4 to 14.04.5 (compare [this job log](https://travis-ci.org/cakephp/acl/jobs/178965268#L13-L19) to [this one](https://travis-ci.org/mikeu/acl/jobs/181145416#L13-L19)), which seems to have broken support for MySQL 5.5. 
Changing the `.travis.yml` file to explicitly install …

Skip abstract (and other uninstantiable) controllers to resolve #110

---

src/AclExtras.php

Using `_checkMethods()` when calling `acoUpdate()` from a controller can cause Exception when instantiating controllers.
In my case i use https://github.com/croogo/croogo. It implements an interface to update ACL.
```php
// In a controller
$AclExtras = new AclExtras();
$AclExtras->startup($this);
$AclExtras->acoUpdate();
```
```php
// $namespace = "App\Controller\UsersController"
$methods = get_class_methods(new $namespace);
```
I have an exception
```
object(RuntimeException) {
[protected] message => 'You cannot configure "Croogo/Nodes.Nodes", it has already been constructed.'
[protected] code => (int) 0
[protected] file => '/var/www/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php'
[protected] line => (int) 76
}
```
```php
// $namespace = "App\Controller\UsersController"
$methods …
```

use get_class_methods() with string instead of instance

---

tests/TestCase/AclExtrasTest.php
tests/TestCase/AclShellTest.php
tests/TestCase/Adapter/CacheDbAclTest.php
tests/TestCase/Adapter/DbAclTest.php
tests/TestCase/Model/Behavior/AclBehaviorTest.php
tests/TestCase/Model/Table/AclNodesTest.php

I've used same method as in [cakephp/bake](https://github.com/cakephp/bake/pull/477/files#diff-9cd97b9850ca4bc60c9b728a10be785aL73) to suppress warnings

3.7 deprecations

---

src/AclExtras.php

One of our CI tools (I think it was Scrutinizer) recently complained about the fact that we were accessing `AclExtras->Shell` directly, without such a property existing on the class itself.  This PR adds it, and `$controller`, as protected properties, with necessary getters and setters in place as well.
I realise this probably breaks BC... if `$Shell` and `$controller` need to be `public` instead I'd be happy to make the necessary adjustments.

Add $Shell and $controller properties to AclExtras

---

src/Controller/Component/AclComponent.php

The text of the exception in the component's constructor is incorrect because of the incorrect using of `sprintf`.

Fix component's constructor error message

---

.gitignore
.travis.yml
composer.json
phpunit.xml.dist
src/AclExtras.php
src/Auth/ActionsAuthorize.php
src/Auth/CrudAuthorize.php
src/Model/Table/AclNodesTable.php
src/Model/Table/AcoActionsTable.php
src/Model/Table/AcosTable.php
src/Model/Table/ArosTable.php
src/Model/Table/PermissionsTable.php
src/Shell/AclExtrasShell.php
src/Shell/AclShell.php
tests/TestCase/AclExtrasTest.php
tests/TestCase/AclShellTest.php
tests/TestCase/Adapter/CacheDbAclTest.php
tests/TestCase/Adapter/DbAclTest.php
tests/TestCase/Adapter/IniAclTest.php
tests/TestCase/Adapter/PhpAclTest.php
tests/TestCase/Auth/ActionsAuthorizeTest.php
tests/TestCase/Auth/CrudAuthorizeTest.php
tests/TestCase/Controller/Component/AclComponentTest.php
tests/TestCase/Model/Behavior/AclBehaviorTest.php
tests/TestCase/Model/Table/AclNodesTest.php
tests/bootstrap.php

I have updated the ACL plugin for CakePHP 4.x.
In addition i created an example application which uses _Authentication_, _Authorization_ _ACL_ and _CakePdf_ as reference implementation:
https://github.com/nook24/blood-pressure

Update ACL Plugin for CakePHP 4.x

---

src/Model/Table/AclNodesTable.php

Fixes incomplete error message `Cake\Core\Exception\Exception: AclNode::node() - Couldn't find {0} node identified by "{1}"`

Fix exception message placeholders

---

src/Model/Table/PermissionsTable.php

there is an deprecation warning in the ACL Plugin since I have updated my Application from CakePHP 4.2.9 to CakePHP 4.3.0:
```
Deprecated (16384): Calling result set method `extract()` directly on query instance is deprecated. You must call `all()` to retrieve the results first. - /vendor/cakephp/acl/src/Model/Table/PermissionsTable.php, line: 104
You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `vendor/cakephp/acl/src/Model/Table/PermissionsTable.php` to  `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file. [CORE/src/Core/functions.php, line 322]
```
fixed with this pull request

fixed deprecation warning in PermissionsTable to work with CakePHP 4.3.x

---

composer.json
phpunit.xml.dist
src/Model/Table/AclNodesTable.php
src/Model/Table/PermissionsTable.php
tests/Fixture/AcoActionsFixture.php
tests/Fixture/AcoTwosFixture.php
tests/Fixture/AcosFixture.php
tests/Fixture/AroTwosFixture.php
tests/Fixture/ArosAcoTwosFixture.php
tests/Fixture/ArosAcosFixture.php
tests/Fixture/ArosFixture.php
tests/Fixture/PeopleFixture.php
tests/TestCase/AclExtrasTest.php
tests/TestCase/Model/Table/AclNodesTest.php
tests/bootstrap.php
tests/schema.php
tests/test_app/Plugin/TestPlugin/config/routes.php
tests/test_app/config/routes.php

- Fixed the PHP 8.1 deprecation of passing non-string to ctype_digit
- Updated testsuite to CakePHP 4.3+
**Refs**
https://wiki.php.net/rfc/deprecations_php_8_1#ctype_function_family_accepts_int_parameters
https://www.php.net/manual/en/function.ctype-digit.php

PHP 8.1 support

---

src/Adapter/DbAcl.php
src/Model/Table/PermissionsTable.php

Fixing issue raised here
[https://github.com/cakephp/cakephp/issues/16158](https://github.com/cakephp/cakephp/issues/16158)
Dynamic properties are deprecated in PHP8.2
[https://php.watch/versions/8.2/dynamic-properties-deprecated](https://php.watch/versions/8.2/dynamic-properties-deprecated)

Fix PHP 8.2 dynamic properties deprecation notices
